#!/usr/bin/env bash
set -eo pipefail -u

volume() {
  pactl get-sink-volume @DEFAULT_SINK@ | grep -o '[0-9]\{1,3\}%' | head -n 1 | sed 's/%//'
}

[[ ${1:-} == 'down' ]] && {
  pactl set-sink-volume @DEFAULT_SINK@ -5%
  printf '\e[33m󰝞 \e[37maudio volume \e[0m%s\n' "$(volume)"
}

[[ ${1:-} == 'up' ]] && {
  VOL=$(volume)
  ((DELTA = VOL <= 95 ? 5 : 100 - VOL))
  pactl set-sink-volume @DEFAULT_SINK@ +$DELTA%
  printf '\e[33m󰝝 \e[37maudio volume \e[0m%s\n' "$(volume)"
}

[[ ${1:-} =~ ^(input|output)$ ]] && {
  [[ $1 == 'input' ]] && SOURCE=1
  [[ $1 == 'output' ]] && SINK=1

  [[ ${SOURCE:-} ]] && ALL=$(pactl list short sources | cut -f2) && DEFAULT='Default Source'
  [[ ${SINK:-} ]] && ALL=$(pactl list short sinks | cut -f2) && DEFAULT='Default Sink'

  default() {
    pactl info | grep "$DEFAULT" | cut -d' ' -f3
  }

  show() {
    DEVICE=$(pactl list "$1" | grep --context=1 "$2" | grep 'Description' | sed -e 's/.*Description: //')
    if [[ $1 == 'sources' ]]; then
      printf '\e[33m \e[37maudio input \e[0m%s\n' "$DEVICE"
    elif [[ $1 == 'sinks' ]]; then
      printf '\e[33m󰓃 \e[37maudio output \e[0m%s\n' "$DEVICE"
    fi
  }

  while true; do
    while IFS= read -r current; do
      if [[ ${SWITCH:-} ]]; then
        [[ ${SOURCE:-} ]] && pactl set-default-source "$current"
        [[ ${SINK:-} ]] && pactl set-default-sink "$current"
        if [[ $(default) == "$current" ]]; then
          [[ ${SOURCE:-} ]] && show 'sources' "$current"
          [[ ${SINK:-} ]] && show 'sinks' "$current"
          exit
        fi
      fi
      [[ $(default) == "$current" ]] && SWITCH=1
    done < <(echo "$ALL")
  done
}

[[ -z ${1:-} || ${1:-} == 'mute' ]] && {
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  [[ $(pactl get-sink-mute @DEFAULT_SINK@ | sed -e 's/Mute: //') == 'yes' ]] &&
    printf '\e[33m󰖁 \e[37maudio \e[0mmuted\n' ||
    printf '\e[33m󰕾 \e[37maudio \e[0munmuted\n'
}

exit 0
