#!/usr/bin/env zsh

set -e

while read -r repo; do

  [[ $2 = '' ]] && local dir=~/code/$repo || local dir=~/code/$2

  if [[ $1 = $repo ]]; then

    echo "fetching $repo"

    if [[ -d $dir ]]; then
      pushd -q $dir && (git checkout master || git checkout main) && git pull --prune && popd -q
    else
      git clone "git@github.com:ApsisInternational/$repo.git" $dir
    fi

  fi

done < $XDG_CACHE_HOME/fetch/repos

