#!/usr/bin/env bash

set -e -o verbose

# https://wiki.archlinux.org/title/Limine
# https://gist.github.com/yovko/512326b904d120f3280c163abfbcb787

[[ $HOST = 'player' ]] || exit 1

# sudo pacman -S --noconfirm \
#   limine

# sudo [ -d /boot/EFI/limine ] || sudo mkdir /boot/EFI/limine
# sudo cp /usr/share/limine/BOOTX64.EFI /boot/EFI/limine/

# sudo efibootmgr \
#   --create \
#   --disk /dev/nvme0n1 \
#   --part 1 \
#   --label 'Limine' \
#   --loader /EFI/limine/BOOTX64.EFI \
#   --unicode

# sudo sbctl sign --save /boot/EFI/limine/BOOTX64.EFI
#
#
### Read more at config document: https://codeberg.org/Limine/Limine/src/branch/v10.x/CONFIG.md
### Auto-generated by limine-entry-tool: https://gitlab.com/Zesko/limine-entry-tool

#timeout: 3
### Note: For "default_entry" to select a sub-entry within an OS menu, modify "/OS name" to "/+OS name" to keep its submenus visible.
# default_entry: 2
# #interface_branding: Your boot manager
# #interface_branding_color: 3
# hash_mismatch_panic: no
#
#
# /+Arch Linux
# ### This OS entry is auto-generated by limine-entry-tool
# comment: Arch Linux
# comment: machine-id=52b40e5453fa41de89eed3132b38584c order-priority=50
#   //linux-lts
#   ### This kernel entry is auto-generated by limine-entry-tool
#   comment: Kernel version: 6.12.63-1-lts
#   comment: kernel-id=linux-lts
#   protocol: linux
#   module_path: boot():/52b40e5453fa41de89eed3132b38584c/linux-lts/initramfs-linux-lts#6cb2da7931fff58f987f7aa23a948a03948e8b95757b836f2709800ddd4e3f1b5a3403cdb6680ad8895c124bcb0088f75d12fd51806af6916c4d391416edc603
#   path: boot():/52b40e5453fa41de89eed3132b38584c/linux-lts/vmlinuz-linux-lts#0b4d3643d18315adcce15af3f2cc7ef23b11caf44d3683179ba3fdb3080f97a2034d96d13dbb5695c008c4d7db6f4f4887aa74b51d7bad6910690922d0f9ed45
#   cmdline: root=/dev/mapper/vg1-root resume=/dev/mapper/vg1-swap rw amd_pstate=active nvidia-drm.modeset=1 quiet loglevel=3 rd.udev.log_level=3
#
#   //linux
#   ### This kernel entry is auto-generated by limine-entry-tool
#   comment: Kernel version: 6.18.2-arch2-1
#   comment: kernel-id=linux
#   protocol: linux
#   module_path: boot():/52b40e5453fa41de89eed3132b38584c/linux/initramfs-linux#37d0c51a3280a3843faacfd2c585e81345a16fb6fa537cf8ee62606cb4bde6e7e88d46678d019e28a983516640999ad99514e969300ad10311b7f96757011bf7
#   path: boot():/52b40e5453fa41de89eed3132b38584c/linux/vmlinuz-linux#5ca1aa3e456afdcdef7206044d7857a11bfacd60f0b2e5811de310223c67f67c36d76436f41a7995059011cf2093a61a8a8e9b11feef14d80191e904438ab3e8
#   cmdline: root=/dev/mapper/vg1-root resume=/dev/mapper/vg1-swap rw amd_pstate=active nvidia-drm.modeset=1 quiet loglevel=3 rd.udev.log_level=3
#
# /Systemd-boot
# ### This EFI entry is auto-generated by limine-entry-tool
# comment: Systemd bootloader
# comment: order-priority=20
# protocol: efi
# path: boot():/EFI/systemd/systemd-bootx64.efi
#
#
# /Windows Boot Manager
# ### This EFI entry is auto-generated by limine-entry-tool
# comment: Windows Boot Manager
# comment: order-priority=20
# protocol: efi
# path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
#
#
# /EFI fallback
# ### This EFI entry is auto-generated by limine-entry-tool
# comment: Default EFI loader
# comment: order-priority=10
# protocol: efi
# path: boot():/EFI/Boot/bootx64.efi
#

# /Arch
#     protocol: linux
#     path: boot():/vmlinuz-linux
#     cmdline: root=/dev/mapper/vg1-root resume=/dev/mapper/vg1-swap rw amd_pstate=active nvidia-drm.modeset=1 quiet loglevel=3 rd.udev.log_level=3
#     module_path: boot():/initramfs-linux.img
#     # module_path: boot():/amd-ucode.img
#
# /Windows
#     protocol: efi
#     path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
# [root@player limine]#
#####################ca1aa3e456afdcdef7206044d7857a11bfacd60f0b2e5811de310223c67f67c36d76436f41a7995059011cf2093a61a8a8e9b11feef14d80191e904438ab3e8

#
