#!/usr/bin/env bash
set -eo pipefail -u

[[ $HOST == 'drifter' ]] && RES='1280x720'
[[ $HOST == 'worker' ]] && RES='1920x1080'

CAM=$(v4l2-ctl --list-devices | grep -m1 '/dev' | tr -d '\t')
[[ -z $CAM ]] && exit 1

ffplay -input_format mjpeg -video_size "$RES" -framerate 30 "$CAM" &>/dev/null
