title    Cachy LTS
sort-key 02
linux    /vmlinuz-linux-cachyos-lts
initrd   /<ucode>.img
initrd   /initramfs-linux-cachyos-lts.img
options  root=/dev/mapper/vg1-root resume=/dev/mapper/vg1-swap rw <params>
